# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  SNYK_TOKEN: '$(SNYKTOKEN)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # - task: SnykSecurityScan@0
    #   inputs:
    #     serviceConnectionEndpoint: 'Snyk EQ AppSec'
    #     testType: 'app'
    #     severityThreshold: 'high'
    #     monitorOnBuild: true
    #     failOnIssues: true
    #     projectName: '[AzPipeline][AppScan]'
    #     organization: 'appsec-5y8'
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerHub'
        repository: 'larskaare/smailandstuff'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
#       arguments: --build-arg SNYK_TOKEN=$(SNYKTOKEN)
        addPipelineData: false
    - task: SnykSecurityScan@0
      inputs:
        serviceConnectionEndpoint: 'Snyk EQ AppSec'
        testType: 'container'
        dockerImageName: 'larskaare/smailandstuff'
        dockerfilePath: 'Dockerfile'
        monitorOnBuild: true
        failOnIssues: true
        projectName: '[AzPipeline][ContainerScan]'
        organization: 'appsec-5y8'
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerHub'
        repository: 'larskaare/smailandstuff'
        command: 'push'
        tags: |
          $(Build.BuildId)
          latest
