name: Scan git commits for secrets

on: [push, pull_request]

jobs:
  scan:
    name: Scan with gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: gitleaks scanning
        uses: larskaare/gitleaks-action@master
